#!/usr/bin/env bash
vscode_name="code-insiders.cmd"
if is-winpath .; then
    echo "Windows path detected; using windows launcher"
    vscode_name="vscode.exe"
else
    echo "Non-Windows path detected; using default launcher"
fi
vscode_loader="$(wwhich $vscode_name | grep -v "cmd")"
"$vscode_loader" "${@}"
